const {Router} = require('express')
const router = Router()
const {renderVistaAdmi} = require('../controllers/vistaAdmi.js')
const {insertarSerie} = require('../controllers/insertarSeries.js')
const {renderEditForm} = require('../controllers/renderEditForm.js')
const {nuevaTemporada} = require('../controllers/agregarTemporada.js')
const {editar} = require('../controllers/editarSerie.js')
const {eliminarSerie} = require('../controllers/eliminarSerie.js')
const {usuarioAutenticado} = require('../config/usuarioAutenticado.js')
const {cerrarSesion} = require('../controllers/cerrarSesion.js')

router.get('/', /*usuarioAutenticado ,*/renderVistaAdmi)
router.post('/',/*usuarioAutenticado,*/insertarSerie)
router.get('/renderEditForm/:id',/*usuarioAutenticado ,*/renderEditForm)
router.post('/editarSerie/:id',usuarioAutenticado,editar)
router.all('/agregar-temporada/:id/cadena/:string',/*usuarioAutenticado,*/nuevaTemporada)
router.get('/eliminarSerie/:id',usuarioAutenticado,eliminarSerie)
module.exports = router