const {Router} = require('express')
const router = Router()
const {renderVistaAdmi} = require('../controllers/vistaAdmi.js')
const {insertarSerie} = require('../controllers/insertarSeries.js')
const {renderEditForm} = require('../controllers/renderEditForm.js')
const {nuevaTemporada} = require('../controllers/agregarTemporada.js')
const {editar} = require('../controllers/editarSerie.js')
const {eliminarSerie} = require('../controllers/eliminarSerie.js')
router.get('/',renderVistaAdmi)
router.post('/',insertarSerie)
router.get('/renderEditForm/:id',renderEditForm)
router.post('/editarSerie/:id',editar)
router.all('/agregar-temporada/:id/cadena/:string',nuevaTemporada)
router.get('/eliminarSerie/:id',eliminarSerie)
module.exports = router